;if(typeof(QTCOMM)=="undefined"){var QTCOMM={}}
String.prototype.replaceAll=function(sFrom, sTo){return this.split(sFrom).join(sTo);}
String.prototype.replacePairs=function(){var s=this;for(var i=0;i<arguments.length;++i){s=s.replaceAll(arguments[i][0],arguments[i][1]);}return s;} 
String.prototype.toHtml=function(){return this.replacePairs.apply(this,String.prototype.toHtml.CONVERT_ARRAY);}
String.prototype.toHtml.CONVERT_ARRAY=[["&","&#38;"],[" ","&nbsp;"],["'","&#39;"],["\"","&#34;"],["/","&#47;"],["<","&#60;"],[">","&#62;"],["\\","&#92;"],["\n","<br />"],["\r",""]];
Date.prototype.format=function(format){var o={"M+":this.getMonth()+1,"d+":this.getDate(),"h+":this.getHours(),"m+":this.getMinutes(),"s+":this.getSeconds(),"q+":Math.floor((this.getMonth()+3)/3),"S":this.getMilliseconds()};if(/(y+)/.test(format)){format=format.replace(RegExp.$1,(this.getFullYear()+"").substr(4-RegExp.$1.length));}for(var k in o){if(new RegExp("("+k+")").test(format)){format=format.replace(RegExp.$1,RegExp.$1.length==1?o[k]:("00"+o[k]).substr((""+o[k]).length));}}return format;}
QTCOMM.getUrlPara=function(paraName,sUrl){if (typeof(sUrl)=='undefined'){sUrl = document.location.href;}var urlRegex = new RegExp(paraName+"=[^&#\?]*", "igm");var para = sUrl.match( urlRegex );if(!para){return "";}var v=para[0];from = v.indexOf( "=" );var paraValue = v.substr(from+1, v.length);while( paraValue.indexOf('<') >= 0 ){paraValue = paraValue.replace('<','');}if( paraValue .indexOf( "#" ) > 0 ){from = paraValue .indexOf( "#" );paraValue = paraValue .substr(0, from );}return paraValue;}
QTCOMM.getCookie=function(name){var arr,reg=new RegExp("(^| )"+name+"=([^;]*)(;|$)");if(arr=document.cookie.match(reg)){return unescape(arr[2])}else{return null}}
QTCOMM.setCookie=function(name,value,expiresd,path,domain,secure){var expdate=new Date();var expires=arguments[2]||null;var path=arguments[3]||"/";var domain=arguments[4]||null;var secure=arguments[5]||false;if(expires){expdate.setMinutes(expdate.getMinutes()+parseInt(expires));}var cookietemp=escape(name)+'='+escape(value)+(expires?'; expires='+expdate.toGMTString():'')+(path?'; path='+path:'')+(domain?'; domain='+domain:'')+(secure?'; secure':'');document.cookie=cookietemp}
QTCOMM.delCookie=function(name){var exp=new Date();exp.setTime(exp.getTime()-1);var cval=QTCOMM.getCookie(name);document.cookie=name+"="+cval+";expires="+exp.toGMTString()}
QTCOMM.getToken=function(){var hash=5381;var str=QTCOMM.getCookie("skey");if(str==null||typeof(str)=="undefined"){str=""}for(var i=0,len=str.length;i<len;++i){hash+=(hash<<5&0x7fffffff)+str.charCodeAt(i)}return hash&0x7fffffff}
QTCOMM.addToken=function(url){if(url&&!(/varcache\_[a-zA-Z0-9\_\-\%]+\.php$/.test(url.split("?")[0]))&&!(/\.js$/.test(url.split("?")[0]))&&QTCOMM.getUrlPara("g_tk",url)==""){if(url.indexOf('?')!=-1){url+="&g_tk="+QTCOMM.getToken();}else{url+="?g_tk="+QTCOMM.getToken();}}return url;}
QTCOMM.FloadJS=function(a,b,d){var src='',charset='';if(typeof(a)=='object'){src=QTCOMM.addToken(a.src);charset=a.charset}else{src=QTCOMM.addToken(a)};var c=document.createElement("script"),e=document.body||document.getElementsByTagName('head')[0],s=document.getElementsByTagName("script"),l=s.length,h=false;c.onerror=function(){c.onreadystatechange=null;if(d!==''&&'function'==typeof(d)){d()}};if(c.readyState){c.onreadystatechange=function(){if(c.readyState=="loaded"||c.readyState=="complete"){c.onreadystatechange=null;if('function'==typeof(b)){b()}}}}else{c.onload=function(){if('function'==typeof(b)){b()}}}while(l){var cs=s[l-1];if(src===cs.src){h=true;break};l--};if(!h){c.src=src;if(charset!=''){c.charset=charset};e.appendChild(c)}else{if('function'==typeof(b)){b()}}}
QTCOMM.attach=function(d,a,c,b){if(d.addEventListener){d.addEventListener(a,c,b)}else{if(d.attachEvent){d.attachEvent("on"+a,c)}}}
QTCOMM.ozreport={data:[],configs:null,timing:{},report:function(opt){if(!opt||!opt.flag){alert("ozreport para error");return};this.configs=opt;if(!this.init()){return};this.pushData();this.send()},init:function(){var perf=(window.webkitPerformance?window.webkitPerformance:window.msPerformance);perf=(perf?perf:window.performance);var timing=perf&&perf.timing;if(timing){this.timing=timing;return true}else{return false}},pushCt:function(){var timing=this.timing;var ct=QTCOMM.getUrlPara('ct');if(ct==""||QTCOMM.getCookie("ct")==1){return};QTCOMM.setCookie("ct","1");ct=parseInt(ct,10);if(ct>11111111&&document.referrer==""&&timing.navigationStart){var d1=this.getCtDiff(ct,new Date(timing.navigationStart));var d2=this.filterArg(d1);if(d2<10000){this.data.push("1="+d2)}}},getCtDiff:function(ct,now){var tzo=(now.getTimezoneOffset()/60)*(-1);var today=Date.UTC(now.getFullYear(),now.getMonth(),now.getDate());return(now.getTime()-today+tzo*3600*1000)*1-ct},send:function(){var url="http://isdspeed.qq.com/cgi-bin/r.cgi?";var flag=this.configs.flag;this.data.push("flag1="+flag[0]);this.data.push("flag2="+flag[1]);this.data.push("flag3="+flag[2]);url+=this.data.join("&");var imgSend=new Image();imgSend.src=url},pushData:function(){var timing=this.timing;this.pushCt();var start=timing.fetchStart;this.data.push("2="+this.filterArg((timing.requestStart-start)));this.data.push("3="+this.filterArg((timing.domContentLoadedEventStart-start)));this.data.push("4="+this.filterArg((timing.loadEventStart-start)))},filterArg:function(d){var max=10000,min=1;if(d<0){return 0}else if(d==0){return min}else if(d>max){return max}else{return d}}};
QTCOMM.pgvSendClickQt=function(hottag){var url='http://pinghot.qq.com/pingd?dm=bbs.lol.qq.com.hot&url=/group/&arg=-&hottag='+escape(hottag.hottag)+'&hotx=9999&hoty=9999&rand='+Math.round(Math.random()*100000);new Image().src=url};
pgvSendClickQt=QTCOMM.pgvSendClickQt;